
version: 2.1
jobs:
  build:
    docker:
      - image: gitpod/workspace-full # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: go build gocalc.go
      - run: ./gocalc